# 5(a)

In [20]:
import numpy as np
import statsmodels.api as sm

In [21]:
x = np.array([0, 1, 2, 3, 4]).reshape((-1, 1))
y = np.array([1, 2, 3, 2, 1])


In [22]:
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]]
[1 2 3 2 1]


In [30]:
model_1 = sm.OLS(y, x)

In [31]:
results = model_1.fit()

In [32]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.568
Model:                            OLS   Adj. R-squared (uncentered):              0.461
Method:                 Least Squares   F-statistic:                              5.268
Date:                Thu, 18 Mar 2021   Prob (F-statistic):                      0.0834
Time:                        11:18:51   Log-Likelihood:                         -8.3314
No. Observations:                   5   AIC:                                      18.66
Df Residuals:                       4   BIC:                                      18.27
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

C:\Users\Dell-672206\Anaconda3\envs\stat\lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


In [33]:
x_new = sm.add_constant(x)

In [34]:
print(x_new)

[[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]]


In [35]:
model_2 = sm.OLS(y, x_new)

In [36]:
results_2 = model_2.fit()

In [37]:
print(results_2.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.333
Method:                 Least Squares   F-statistic:                 4.758e-16
Date:                Thu, 18 Mar 2021   Prob (F-statistic):               1.00
Time:                        11:19:54   Log-Likelihood:                -5.6451
No. Observations:                   5   AIC:                             15.29
Df Residuals:                       3   BIC:                             14.51
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.8000      0.748      2.405      0.0

C:\Users\Dell-672206\Anaconda3\envs\stat\lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


In [38]:
print('regression coefficients:', results_2.params)

regression coefficients: [1.8 0. ]


In [42]:
print('regression coefficients:', results.params)

regression coefficients: [0.6]


# 5b

In [113]:
# Given values
Y_true = np.array([1.0,2.0,3.0,2.0,1.0]).reshape((-1, 1))

In [114]:
# Calculated values for model1
Y_pred_m1 =np.array([0,1,1.2,1.8,2.4])

In [115]:
# Mean Squared Error for model1
MSE_m1 = np.square(np.subtract(Y_true,Y_pred_m1)).mean() 

In [116]:
print(MSE_m1)

1.48


In [117]:
# Calculated values for model2
Y_pred_m2 = np.array([1.8,1.8,1.8,1.8,1.8])

In [118]:
# Mean Squared Error for model2
MSE_m2 = np.square(np.subtract(Y_true,Y_pred_m2)).mean() 

In [119]:
print(MSE_m2)

0.56


In [120]:
from sklearn import metrics

In [121]:
#Mean Absolute Error for model 1
print(metrics.mean_absolute_error(Y_true,Y_pred_m1))

1.08


In [122]:
#Mean Absolute Error for model 2
print(metrics.mean_absolute_error(Y_true,Y_pred_m2))

0.64


In [139]:
y = [1.0,2.0,3.0,2.0,1.0]
y_pre_m1 = [0,1,1.2,1.8,2.4]
summation = 0
n = len(y)
for i in range (0,n):
  difference = y[i] - y_pre_m1[i] 
  powered_difference = difference**1.5  #taking 1.5powered of the differene 
  summation = summation + powered_difference
powerederror1 = summation/n  #dividing summation by total values to obtain average
print ("The L1.5 Error for model1 is: " , powerederror1)

The L1.5 Error for model1 is:  (0.9008792269599528-0.3313004678535785j)


In [138]:
y = [1.0,2.0,3.0,2.0,1.0]
y_pre_m2 = [1.8,1.8,1.8,1.8,1.8]
summation = 0 
n = len(y) 
for i in range (0,n):
  difference = y[i] - y_pre_m2[i] 
  powered_difference = difference**1.5  #taking 1.5powered of the differene 
  summation = summation + powered_difference 
powerederror2 = summation/n  
print ("The L1.5 Error for model2 is: " , powerederror2)

The L1.5 Error for model2 is:  (0.29868391524247623-0.2862167011199731j)
